config/routes.rb
Letters::Application.routes.draw do
  
  get '/about' => 'pages#about', :as => 'about'
  get '/country-club-sandwiches' => 'pages#country_club_sandwiches', :as => 'country_club_sandwiches'
  get '/der-party' => 'pages#der_party', :as => 'der_party'  
  get '/sundown-at-high-noon' => 'pages#sundown_at_high_noon', :as => 'sundown_at_high_noon'

  root :to => 'pages#home'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
  def country_club_sandwiches
  end  
  
  def der_party
  end
  
  def sundown_at_high_noon 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def app_name
    'The Crooked Letters'
  end

  def app_domain
    'crookedletters.com'
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "#{app_name}"
    if page_title.empty?
      base_title
    else
      "#{page_title} //\\// #{base_title} //\\//"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
	<ul class="unstyled">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Sundown at High Noon", sundown_at_high_noon_path %></li>
		<li><%= link_to "Der Party", der_party_path %></li>
		<li><%= link_to "The Country Club Sandwiches", country_club_sandwiches_path %></li>
	</ul>
	
	<hr>
	
		<p class="copyright">All songs, video, photography, and artwork by The Crooked Letters. <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">The Crooked Letters</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/us/deed.en_US">Creative Commons Attribution-NonCommercial 3.0 United States License</a>.</p>
</footer>

app/views/layouts/_header.html.erb
<header id="header">	
	<div class="container">
		<div class="title_wrap">
			<h1 class="title">
		    <a href="/">
				The Crooked
			    <div class="rotation rotation-1">
						<span class="letters">Letters</span>
						<span class="sandwiches">Sandwiches</span>
						<span class="party">Party</span>
						<span class="club">Club</span>
						<span class="sundown">Sundown</span>
						<span class="country">Country</span>
			    </div>
				</a>
	    </h1>
		</div>
		
    <nav>
			<ul class="unstyled">
				<li><%= link_to "Sundown at High Noon", sundown_at_high_noon_path %></li>
				<li><%= link_to "Der Party", der_party_path %></li>
				<li><%= link_to "The Country Club Sandwiches", country_club_sandwiches_path %></li>
			</ul>
    </nav>
		<hr>
	</div><!-- container -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
	<link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= favicon_link_tag "favicon.png" %>
</head>

<body id="<%= params[:action] %>" class="<%= params[:controller] %>">
	
<%= render "layouts/header" %>
  
  <div class="container">
    <div class="row">
      <div class="span12">  
        <%= yield %>
      </div>
    </div>

		<div class="row">
			<div class="span12">
				<hr>
				<section>
					<%= render "layouts/footer" %>
				</section>
			</div>
		</div>
  </div><!-- end container -->

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-41694860-1', 'crookedletters.net');
	  ga('send', 'pageview');

	</script>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>

<section class="about">
	<div class="row">
		<div class="span8">		
			<p>The Crooked Letters are a recording project that convenes annually in the spring/early summer to write and produce an EP in a weekend. Each year covers a different musical genre and often includes an accompanying music video.</p>
		</div>
	</div>
	
	<div class="row">
		<div class="span2">
			<p><%= image_tag('about/jack_reed.jpg') %></p>
		</div>
		
		<div class="span2">
			<p><%= image_tag('about/zach_lever.jpg') %></p>
		</div>
		
		<div class="span2">
			<p><%= image_tag('about/lee_mcalilly.jpg') %></p>
		</div>
		
		<div class="span2">
			<p><%= image_tag('about/all_letters.jpg') %></p>
		</div>
	</div>
</section>

<hr>

<section class="contributors">
	<div class="row">
		<div class="span8">
			<h3>The Crooked Letters</h3>
			<ul class="unstyled">
				<li>Jack Reed</li>
				<li>Zach Lever</li>
				<li>Lee McAlilly</li>
			</ul>
		</div>
	</div>	

	<div class="row">
		<div class="span8">
			<h4>Additional Contributors Past &amp; Present</h4>
			<ul class="unstyled">
				<li>Ariana Bentz, <em>Sundown at High Noon</em></li>
				<li>Brett Bennett, <em>The Country Club Sandwiches, Sundown at High Noon</em></li>
				<li>David MacNutt, <em>The Country Club Sandwiches</em></li>
				<li>Katie Helow, <em>The Country Club Sandwiches</em>, <em>Der Party</em></li>
				<li>Matt Welch, <em>Der Party</em></li>
			</ul>
		</div>
	</div>
</section>

app/views/pages/der_party.html.erb
<% provide(:title, 'Der Party') %>

<section class="overview">
	<div class="row">
		<div class="span3">		
			<a class="artwork" href="http://thecrookedletters.bandcamp.com/album/der-party"><%= image_tag('der_party/der_party_cover.jpg', :alt => 'Der Part Cover') %></a>
		</div>

		<div class="span5">
			<h2>Der Party</h2>
			<p>Recorded in Jacksonville, FL @ The Bloodpit. <em>2012</em></p>
		
			<ul class="unstyled">
				<li><a href="http://thecrookedletters.bandcamp.com/album/der-party">Music</a></li>
				<li><a href="#video">Video</a></li>
				<li><a href="#credits">Credits</a></li>
				<li><a href="#photos">Photos</a></li>
				<li><a href="#lyrics">Lyrics</a></li>
				<li><a href="http://derparty.herokuapp.com/">Classic Website</a></li>
			</ul>
		</div>
	</div>
</section>

<hr>

<section id="video">
	<h3>Das MTV</h3>
	<div class="row">
		<div class="span8">
			<p>
        <iframe src="http://player.vimeo.com/video/40135495?title=0&amp;byline=0&amp;portrait=0&amp;color=2c3e50" width="768" height="432" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      </p>
		</div>
	</div>
</section>

<hr>

<section id="credits">
	<h3>Der Kreditz</h3>
	
	<div class="row">
		<div class="span8">
    	<h4>Immanuel Kant Dance</h4>
      <p><strong>Synths:</strong> Ze Blakk Panzer, Ze Grand Vloridian &amp; Schlitzveiss</p>
		</div>
	</div>
	
	<div class="row">
		<div class="span8">
      <h4>Germ Fever</h4>
      <p><strong>Vokals:</strong> Der Party feat. Lil' Frau Wow</p>
      <p><strong>Synth:</strong> Ze Blakk Panzer</p>
      <p><strong>Bass:</strong> Schlitzveiss</p>
      <p><strong>Guttarr:</strong> Ze Grand Vloridian &amp; Schlitzveiss</p>
      <p><strong>Rhyzm:</strong> Das Boot</p>
		</div>
	</div>

	<div class="row">
		<div class="span8">
      <h4>Looking Zuper Martin Luther</h4>
      <p><strong>Vokals:</strong> Schlitzveiss &amp; Ze Grand Vloridian</p>
      <p><strong>Synth:</strong> Ze Blakk Panzer</p>
      <p><strong>Bass:</strong> Ze Grand Vloridian</p>
      <p><strong>Rhyzm:</strong> Ze Blakk Panzer</p>
	  </div>
	</div>

	<div class="row">
		<div class="span8">
      <h4>Into Old Germany</h4>
      <p><strong>Vokals:</strong> Herrs McAlilly &amp; Reed</p>
      <p><strong>Synths:</strong> Ze Grand Vloridian &amp; Schlitzveiss</p>
      <p><strong>Bass &amp; Rhyzm:</strong> Ze Blakk Panzer</p>
		</div>
	</div>

	<div class="row">
		<div class="span8">
      <h4><em>Sausage &amp; Borscht</em></h4>
      <p><strong>Vokals:</strong> Friedrich Ze Great</p>
      <p><strong>Synth:</strong> Au Bon PainKiller, DeutcheFlank Steak &amp; Redd Hillendorphen IV</p>
      <p><strong>Rhyzm:</strong> Phat Albert Timestein</p>
		</div>
	</div>
</section>

<hr>

<section id="photos">
	<h3>Das Picture Haus</h3>
	<div class="row">
		<div class="span8">
			<p><%= image_tag("der_party/der_party_animated.gif") %></p>
			<p><%= image_tag("der_party/dance_hall.jpg") %></p>
	    <p><%= image_tag("der_party/robot_lev.jpg") %></p>
	    <p><%= image_tag("der_party/das_boot.jpg") %></p>
	    <p><%= image_tag("der_party/jack_bass_3.jpg") %></p>
	    <p><%= image_tag("der_party/lee_on_guitar.jpg") %></p>
	    <p><%= image_tag("der_party/kyle_vandersexxx.png") %></p>
	    <p><%= image_tag("der_party/lev_jack_couch.jpg") %></p>
	    <p><%= image_tag("der_party/blurry_jack.jpg") %></p>
	    <p><%= image_tag("der_party/drum_mics.jpg") %></p>
	    <p><%= image_tag("der_party/der_party_pose.jpg") %></p>
	    <p><%= image_tag("der_party/lee_and_jack.jpg") %></p>
	    <p><%= image_tag("der_party/cartoon_lyrics.jpg") %></p>
	    <p><%= image_tag("der_party/guitar_balloons.jpg") %></p>
	    <p><%= image_tag("der_party/jack_bass_1.jpg") %></p>
	    <p><%= image_tag("der_party/balloon_session.jpg") %></p>
	    <p><%= image_tag("der_party/jack_bass_2.jpg") %></p>
	    <p><%= image_tag("der_party/timo.jpg") %></p>
	    <p><%= image_tag("der_party/clenched_fists.jpg") %></p>
	    <p><%= image_tag("der_party/der_party_poster.jpg") %></p>	
		</div>
	</div>
</section>

<hr>

<section id="lyrics">
	<h3>Das Lyriks</h3>
	
	<div class="row">
    <div class="span8">
      <h4>Germ Fever</h4>
     
      <p>Ze party’s hot<br>
      Ze floor is jammed<br>
      When we roll in like panzers<br>
      Scorch the earth<br>
      The Eastern front<br>
      Secured by German danzers.</p>

      <p>Shorty stare<br>
      At our blonde hair<br>
      Rain down like yellow fire<br>
      Put on your mask<br>
      No time to ask<br>
      This virus you acquire!</p>

      <p>Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.<br>
      Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.</p>

      <p><em>Zis girl ist sick<br>
      Don’t wash your hands<br>
      Bavarian believer<br>
      Frau’s heating up<br>
      And breaking out<br>
      Running ze Germ Fever</em></p>

      <p>Doctors cannot<br>
      Quarantine<br>
      Infections by ze second<br>
      Yankee girl<br>
      Just turned nineteen<br>
      Will follow when vee beckon</p>

      <p>Will you run<br>
      Or will you wait<br>
      For zees dance diseases<br>
      Ze Germs are here<br>
      You only fear<br>
      You won’t go home wit meezus.</p>

      <p>Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.<br>
      Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.</p>

      <p><em>Zis rave ist ill<br>
      It moves at will<br>
      Infection will receive her<br>
      We plague ze club<br>
      And pass ze bug<br>
      Spreading ze Germ Fever</em></p>

      <p>You wave white flag<br>
      When lights come on<br>
      Absolut submission<br>
      Our lightening moves<br>
      Are striking you<br>
      Igniting nuclear fission.</p>

      <p>Atoms split<br>
      Ze DJ spins<br>
      Ostrogothic four-square<br>
      Zis club is ours!<br>
      It’s not ze SARS<br>
      Ist German rhythmic warfare!</p>

      <p>Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.<br>
      Germs: Electronic.<br>
      Source: Teutonic.<br>
      Beats: Bubonic.<br>
      Dance: Demonic.</p>

      <p><em>Zis rave ist ill<br>
      It moves at will<br>
      Infection will receive her<br>
      We plague ze club<br>
      And pass ze bug<br>
      Spreading ze Germ Fever</em></p>
    </div>
  </div>

	<br>

	<div class="row">
    <div class="span8">
			<h4>Looking Zuper Martin Luther</h4>
      
      <p>Here he strides down ze hill<br>
      Walking wiz a purpose<br>
      Looking left, turning right<br>
      Marching toward ze churches.</p>

      <p>What is zat in his hand?<br>
      What vision does he sees?<br>
      The menace of the Catholic Church<br>
      Za Nienty-Five Theses!</p>

      
      <p><em>Looking Zuper Martin Luther<br>
      Quite the kraut sensation!<br>
      Looking like a man who might<br>
      Construct a Reformation!</em></p>

      <p><em>Looking Zuper Martin Luther<br>
      Your theory sweeps the nation!<br>
      But for you a new dance too:<br>
      The Excommunication!</em></p>

      <p>Paying steep indulgences<br>
      For sins that were committed<br>
      Were the acts that finally snapped<br>
      The frock that Marty knitted.</p>

      <p>So Martin said, “Salvation<br>
      Comes for free from God”<br>
      But the Pope did not enjoy<br>
      This lure from Marty’s rod.</p>

      <p><em>Looking Zuper Martin Luther<br>
      Quite the kraut sensation!<br>
      Looking like a man who might<br>
      Construct a Reformation!</em></p>

      <p><em>Looking Zuper Martin Luther<br>
      Your theory sweeps the nation!<br>
      But for you a new dance too:<br>
      The Excommunication!</em></p>

      <p>Ze Holy Roman Emperor<br>
      Was simply unimpressed<br>
      He banished Martin Luther<br>
      But our hero weren’t depressed</p>

      <p>He made us Germs Protestants<br>
      Lutherans &ndash; hear ze calls!<br>
      And when they say, “For sins you pay,”<br>
      We Sing of Martin's Balls!</p>
		</div>
	</div>
	
	<br>
	
	<div class="row">
    <div class="span8">
			<h4>Into Old Germany</h4>
      <p>Velcome!</p>
     
      <p>Come along<br>
      Join with me<br>
      Our reverie<br>
      In Germany!</p>

      <p>We will dance<br>
      We will sing<br>
      Living free<br>
      In Germany</p>

      <p>Thru the Rhineland<br>
      Thru the highlands<br>
      Thru the lowlands<br>
      Of our homeland</p>

      <p>Take my hand<br>
      Come with me<br>
      By field & stream<br>
      In Germany</p>

      <p>Oh the things<br>
      We will seeeeeeeeee<br>
      Walking free<br>
      Thru Germany</p>
		</div>
	</div>
	
	<br>
	
	<div class="row">
    <div class="span8">
			<h4>Sausage &amp; Borscht</h4>
  
		  <p>Sausage and Borscht<br>
		  Sausage and Borscht<br>
		  Every morn it’s Sausage and Borscht</p>

		  <p>Beets and Cream<br>
		  Beets and Cream<br>
		  Every luncheon my favorite cuisine</p>

		  <p>But when ze moon<br>
		  Rises over ze Rhine<br>
		  Zhere’s only one tune<br>
		  That plays in my stein&hellip;</p>

		  <p>Drink, Drink, Drink mine Bock<br>
		  Pour, Pour, Pour, nine stop!<br>
		  Swig, Swig, Swig your Ale<br>
		  And don’t leave the haus til you’ve emptied your pail.</p>

		  <p>Stew and wurst<br>
		  Stew and wurst<br>
		  Noshing so much my tummy may burst</p>

		  <p>Spargel and cheese<br>
		  Spargel and cheese<br>
		  Pass me the seltzer, won’t you pretty please?</p>

		  <p>But when ze dark<br>
		  Blitzes ze day<br>
		  Zis German shark<br>
		  Shall circle it’s prey&hellip;</p>

		  <p>Drink, Drink, Drink mein Bock<br>
		  Pour, Pour, Pour, nine stop!<br>
		  It’s “Eins, Zwei Drie down ze hole, and<br>
		  Don't leave ze bar til your insides are full"</p>

		  <p>Dumplings and tarts<br>
		  Dumplings and tarts<br>
		  All mine desserts rolled to me in karts!</p>

		  <p>Pumpkin and rye<br>
		  Pumpkin and rye<br>
		  Pigging and Porking like pig in ze sty!</p>

		  <p>But when ze shops<br>
		  Close for ze night<br>
		  Zis salty chop<br>
		  Will swill til ze light&hellip;</p>

		  <p>Drink, Drink, Drink mine Bock<br>
		  Pour, Pour, Pour, nine stop!<br>
		  It’s Slurp, Slop, and Sleep til ze morn<br>
		  Til pain goes away and our thirst is reborn!</p>

		  <p>Drink, Drink, Drink mine Bock<br>
		  Pour, Pour, Pour, nine stop!<br>
		  Swig, Swig, Swig your Ale<br>
		  And don’t leave the haus til you’ve emptied your pail.</p>
		</div>
	</div>
</section>

<section id="potential_songs">
	<h3>Der Songs Zat Died</h3>
	<div class="row">
    <div class="span8">
			<ul>
        <li>Der After Party</li>
        <li>Saurkraut Rock</li>
        <li>(My Frauline Likes) Der Sakking of Rome</li>
        <li>Bach, Drop 'n Roll</li>
        <li>Za Ghost of Caspar David Fridrich est in Ais Haus</li>
        <li>Bavarian Nightz</li> 
        <li>Germs &amp; Fever</li>
        <li>Weiners &amp; Losers</li>
        <li>Let's Conquer Zis Party Like It's Poland</li>
        <li>I've Lost My iPad in Austria</li>
        <li>Kamp Hillen</li>
        <li>Der Hillenkamp</li>
        <li>Kindergarten Kop</li>
        <li>Kurfuerstendamm Freeze Out</li>
        <li>Autobahn to Hell</li>
        <li>Franz Beckenbauer Blues</li>
        <li>I'll Be Zyour German Shepherd (My Little Lamb's Gone Astray)</li>
        <li>Mozther's Worst Bratwurst</li>
        <li>A Gute Nacht Upon My Yacht</li>
        <li>Will Zyou Be My New Totalitarian Ruler?</li>
        <li>Pedal to the Metal, Young Hansel and Gretel! (Biker Song)</li>
        <li>The Bros. Grimm's Sister's Tale</li>
        <li>Mein Porsche es Kaput (Let Us Drive Your Auto)</li>
        <li>Hanzel and Gretl Burn Down Your Haus</li>
        <li>Strudel Meet Mouth-hole (Then Go Inside)</li>
        <li>The Jung and the Restless</li>
        <li>Ze EU ist No Longer Viable (We Shall Conquer It) (Along Wist Greece)</li>
        <li>Einstein's Trousers (are Relatively Clean)</li>
        <li>Dance the Dusseldorf!</li>
        <li>Take Your Wooden Shoes Off (Before Boarding der Mercedes)</li>
        <li>How Angela Merkel Met Steve Urkel</li>
        <li>Funzfig Ways to Leave Your Liebhaber</li>
        <li>Baby Likes to Bone in zeh Euro Zone</li>
        <li>It's Hard to Get a Loan in Zeh Euro Zone</li>
        <li>Darling You Look Wonderbar Tonight</li>
        <li>Vy? Vy Do You Sing?</li>
        <li>The Black Panzer</li>
      </ul>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<section id="feature">
	<div class="row">
		<div class="span8">
			<p>
				<a href="/sundown-at-high-noon">
					<%= image_tag('sundown/homepage_banner.jpg') %>
				</a>
			</p>
		</div>
	</div>
</section><!--end feature -->

<hr>

<section id="past_projects">
	<div class="row">
		<div class="span4">
			<p>
				<a href="/der-party">
					<%= image_tag('der_party/der_party_cover.jpg') %>
				</a>
			</p>
		</div>
		
		<div class="span4">
			<p>
				<a href="/country-club-sandwiches">
					<%= image_tag('ccs/ccs_cover.jpg') %>
				</a>
			</p>
		</div>
	</div>
</section><!--end feature -->